### ISSUE TITLE
undocumented nucmer option -G, --genome 

### ISSUE THREAD

**Issue by caspargross** [mummer4/mummer#109]
I have not found any documentation of the `-G, --genome` option for nucmer. This option is  only visible with `--full-help` and not included in the `docs/nucmer.README` .
The description only says: `Map genome to genome (long query sequences)`

The descriptions suggests to help with performance for large genome alignment, however I would like to get more information about what this options actually does and if it has any drawbacks. Is there any documentation of this feature that I am missing?

**Comment by splaisan** [comment]
I second  Caspar here and would like to read more about combining --mum with --large and or --Genome in the case of alignment of a draft assembly against a more complete assembly (pseudochromosomes).

Are these hidden parameters mutually exclusive or complementary and what should be best applied to avoid >300h computation (>280GB RAM used) for two genomes of 700Mb when applying --max-match ?

Thanks

**Comment by caspargross** [comment]
switching to minimap2 for pairwise genome alignment solves all performance issues ;)

**Comment by splaisan** [comment]
> switching to minimap2 for pairwise genome alignment solves all performance issues ;)

nice but can you share how you create dotplot from the minimap2 results to get visuals comparable to nucmer and mummerplot

**Comment by caspargross** [comment]
Here is a web application to plot .paf files or create alignments:
http://dgenies.toulouse.inra.fr/

**Comment by splaisan** [comment]
thanks a lot @caspargross, I knew DGenies for the full making of dotplots but did not notice it could take precomputed paf.
Cheers
