### ISSUE TITLE
delta-filter no response

### ISSUE THREAD

**Issue by zpliu1126** [mummer4/mummer#149]
I am try to filter the `.delat` file which  generated by `nucmer`

there are the steps I used
```bash
 # nucmer
nucmer --mum -c 90 -l 40 -p A1Chr01_vs_A2  A1.fa  A2.fa
 # delta-filter
delta-filter  -m ./A1Chr01_vs_A2.delta  >A1Chr01_vs_A2_filter.delta
```
I got a `330M ` delta file  by `nucmer` but when I run the `delta-filer` it without any response  for 24h。so I kill it，Is there any problem here。

**Comment by cclaudel-hub** [comment]
I observe the same thing:
#nucmer
nucmer --batch 1 -c 500 -b 500 -l 200 -p genome1Masked_genome2Masked genome1Masked.fasta genome2Masked.fasta
delta file with 621M

#delta-filter
delta-filter -m -i 90 -l 200 genome1Masked_genome2Masked.delta > out_m_i90_l200_ genome1Masked_genome2Masked.delta&

The output is empty after 17h and the program is always running. 
Same thing with a 1.4 G delta file empty after 40h.
It is normal?
Thanks for your help

**Comment by Zefeng-Wu** [comment]
I have run the delta-filter for more than one week, and there still no any result

**Comment by Jnhcau** [comment]
Has anyone solved it？
