### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by fnollet** [mummer4/mummer#17]
It seems there is a error at compile time:

src/essaMEM/mummer.cpp:221:6: error: #elif with no expression
 #elif
      ^
make[1]: *** [src/essaMEM/mummer.o] Error 1

Replacing the "elif" with "else" fixes the issue, but have no idea if this is the "right" solution. I am not a (C) programmer...

An unrelated question: 
Can this new version also be compiled using -DSIXTYFOURBITS in CFLAGS to support larger genomes?
See: https://iamphioxus.org/2016/02/11/compiling-64-bit-mummer/

Thanks
Filip Nollet

**Comment by gmarcais** [comment]
This bug is fixed in the develop branch.
The SIXTYFOURBITS is not necessary. Large genomes are supported by default.
