### ISSUE TITLE
ERROR: Could not parse delta file, out.delta error no: 002

### ISSUE THREAD

**Issue by ylevmirom** [mummer4/mummer#194]
Hi, 
i ran nucmer with this command: 
`nucmer --maxmatch -c 100 -b 500 -l 50`

and when trying to run delta.filter im getting this error: 
`ERROR: Could not parse delta file, out.delta error no: 002`
what could be the reason? 

thanks,

Yael

**Comment by 6YuHao** [comment]
> Hi, i ran nucmer with this command: `nucmer --maxmatch -c 100 -b 500 -l 50`
> 
> and when trying to run delta.filter im getting this error: `ERROR: Could not parse delta file, out.delta error no: 002` what could be the reason?
> 
> thanks,
> 
> Yael
do you solve it  ?
I need your hlelp. I have the same problem
