### ISSUE TITLE
defined(%hash) is deprecated

### ISSUE THREAD

**Issue by sjackman** [mummer4/mummer#2]
Do you have a fix for https://sourceforge.net/p/mummer/bugs/15/? I'm running into it with Linuxbrew: https://github.com/Linuxbrew/homebrew-science/pull/13

**Comment by gmarcais** [comment]
Are you still using MUMmer3? Do you want to give the latest release of MUMmer4 a spin? Even though it is marked alpha, this fourth iteration should be quite stable. And this bug in mummerplot is indeed fixed.

The command line MUST be backward compatible to version 3. If not, please do report a bug.

**Comment by sjackman** [comment]
Would you be comfortable tagging a stable release of MUMmer 4? Homebrew-Science has a policy of packaging only stable software releases.

**Comment by gmarcais** [comment]
I should be able to do that soon.

**Comment by sjackman** [comment]
Great. Thanks, Guillaume.

**Comment by sjackman** [comment]
Hi, Guillaume. Is a stable release of MUMmer 4.0 imminent?
