### ISSUE TITLE
Method for defining SIXTYFOURBITS

### ISSUE THREAD

**Issue by cmdcolin** [mummer4/mummer#20]
I was getting the error about suffix tree construction failing and was wondering if I should still follow this resolution mentioned here? I was going to try mummer 4 but the file path and variable didn't appear defined in the codebase http://seqanswers.com/wiki/Talk:MUMmer

**Comment by gmarcais** [comment]
This variable is not needed anymore. Large genome is supported out of the box.

**Comment by cmdcolin** [comment]
I think my $PATH was really messed up and referring to an old version of mummer maybe. Is there a --version flag for the program to check?
