### ISSUE TITLE
mummerplot command shows '-t' for both 'title' and 'terminal'

### ISSUE THREAD

**Issue by splaisan** [mummer4/mummer#201]
Dear developer,
Can you please clarify what is correct below (from 'mummerplot --help')

```
    -t|terminal     Set the output terminal to x11, postscript or png
                    --x11 --postscript --png (default 'x11')
    -t|title        Specify the gnuplot plot title (default none)
```
I guess that the terminal option should be instead one of --x11, --png, or --postscript without -t 
Is this correct? (should be edited in the help text)
thanks

**Comment by juliadouglasf** [comment]
Commenting to also request clarification in the help text. I've been using `-png` to create my desired output, but I figured that out without help text.

**Comment by splaisan** [comment]
I should have written 'maybe this could be more clear from the help text' for people like me who are less gifted.

**Comment by juliadouglasf** [comment]
Perhaps my comment wasn't clear. I wanted to support this issue because I also feel that the help text is lacking.

**Comment by splaisan** [comment]
In that case my appologies, i indeed understood your comment in a less supportive sense.😅
