### ISSUE TITLE
Added #include <cstdint> to allow compiling with newer versions of gcc

### ISSUE THREAD

**Issue by tbenavi1** [mummer4/mummer#203]
Hello, 

According to https://gcc.gnu.org/gcc-13/porting_to.html, the \<cstdint\> header needs to be explicitly added in order to be able to compile with GCC13.

I added #include \<cstdint\> to include/mummer/48bit_iterator.hpp and include/mummer/48bit_index.hpp and was able to compile successfully. Thank you.

**Comment by A-N-Other** [comment]
https://github.com/mummer4/mummer/pull/199 👀

**Comment by gmarcais** [comment]
This is in the development branch now.
