### ISSUE TITLE
postnuc: postnuc.cc:1427: long int revC(long int, long int): Assertion `Len - Coord + 1 > 0' failed. Aborted (core dumped)

### ISSUE THREAD

**Issue by sybsun** [mummer4/mummer#21]
~/software/jabba-evaluate$ dnadiff /home/syb/dataset/e.coli/sequence.fasta /home/syb/software/jabba_output/Jabba-longreads.fasta 
Building alignments
1: PREPARING DATA
2,3: RUNNING mummer AND CREATING CLUSTERS
 reading input file "out.ntref" of length 4641653
construct suffix tree for sequence of length 4641653
(maximum reference length is 536870908)
 (maximum query length is 4294967295)
process 46416 characters per dot
....................................................................................................
CONSTRUCTIONTIME /usr/bin/mummer out.ntref 1.36
reading input file "/home/syb/software/jabba_output/Jabba-longreads.fasta" of length 245376614
matching query-file "/home/syb/software/jabba_output/Jabba-longreads.fasta"
 against subject-file "out.ntref"
COMPLETETIME /usr/bin/mummer out.ntref 157.01
SPACE /usr/bin/mummer out.ntref 240.39

**_`4: FINISHING DATA`
postnuc: postnuc.cc:1427: long int revC(long int, long int): Assertion `Len - Coord + 1 > 0' failed.
Aborted (core dumped)
ERROR: postnuc returned non-zero
ERROR: Failed to run nucmer, aborting._**

**Comment by gmarcais** [comment]
This looks like the output of nucmer from MUMmer3, not MUMmer4. I do not maintain that version. This is what the outup looks like with MUMmer4:
```
$ dnadiff B_anthracis_contigs.fasta B_anthracis_Mslice.fasta
Building alignments
Filtering alignments
Extracting alignment coordinates
Analyzing SNPs
Extracting alignment breakpoints
Generating report file
```
