### ISSUE TITLE
installation issue

### ISSUE THREAD

**Issue by mahulchak** [mummer4/mummer#22]
Hi,
 I tried the instructions for installations starting with 
./configure --prefix=/path/to/install
but I get
bash: ./configure: No such file or directory
thanks.

**Comment by gmarcais** [comment]
2 options:
- Use the file `mummer-4.0.0beta.tar.gz` from the release. It contains everything you need.
- Make sure you have autoconf/automake/libtool installed and run `autoreconf -fi` in the development tree.
