### ISSUE TITLE
dnadiff error 

### ISSUE THREAD

**Issue by sybsun** [mummer4/mummer#26]
dnadiff sequence.fasta  reads.fasta -p 50long
Building alignments
1: PREPARING DATA
2,3: RUNNING mummer AND CREATING CLUSTERS
\# reading input file "50long.ntref" of length 4641653
\# construct suffix tree for sequence of length 4641653
\# (maximum reference length is 536870908)
\# (maximum query length is 4294967295)
\# process 46416 characters per dot
\#....................................................................................................
\# CONSTRUCTIONTIME /usr/bin/mummer 50long.ntref 2.31
\# reading input file "/50long/e.coli.correctedReads.fasta" of length 112457574
\# matching query-file "/50long/e.coli.correctedReads.fasta"
\# against subject-file "50long.ntref"
\# COMPLETETIME /usr/bin/mummer 50long.ntref 126.30
\# SPACE /usr/bin/mummer 50long.ntref 112.41
4: FINISHING DATA
postnuc: postnuc.cc:1427: long int revC(long int, long int): Assertion `Len - Coord + 1 > 0' failed.
Aborted (core dumped)
ERROR: postnuc returned non-zero
ERROR: Failed to run nucmer, aborting.

**Comment by gmarcais** [comment]
This is MUMmer4 not MUMmer4.
