### ISSUE TITLE
no configure script neither in github repo nor in source code release tarball

### ISSUE THREAD

**Issue by samfux84** [mummer4/mummer#28]
Hi,

I tried to install mummer4 on our HPC cluster. The installation instructions say that one should run the configure script, but there is none.

When running autoconf or autoreconf to create the configure script, everything looks good until one tries to run the configure script that was created:

```
[sfux@develop01 mummer-4.0.0beta1]$ ./configure --prefix=/cluster/apps/gdc/mummer/4.0.0b1
configure: error: cannot find install-sh, install.sh, or shtool in "." "./.." "./../.."
```

Any idea ?

**Comment by gmarcais** [comment]
You have to download the file  [mummer-4.0.0beta1.tar.gz](https://github.com/mummer4/mummer/releases/download/v4.0.0beta1/mummer-4.0.0beta1.tar.gz). It does contain a `configure` script.

If you start from the github tree, run `autoreconf -fi`.

**Comment by samfux84** [comment]
Thank you for the hint. This works fine.
