### ISSUE TITLE
libumdmummer.so.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by xxz19900** [mummer4/mummer#48]
!!! 2017-12-01 00:25:16  Doing step 20:  Getting overlaps 
!!! 2017-12-01 00:25:16  Running: /usr/local/bin/nucmer -maxmatch -c 40 m_i_20.ref.seq m_i_20.qry.seq -p m_i_20
/usr/local/bin/nucmer: error while loading shared libraries: libumdmummer.so.0: cannot open shared object file: No such file or directory
!!! 2017-12-01 00:25:16  Command: /usr/local/bin/nucmer -maxmatch -c 40 m_i_20.ref.seq m_i_20.qry.seq -p m_i_20 exited with status: 127
!!! END - Elapsed time: 0d 0h 2m 42s

**Comment by gmarcais** [comment]
If you installed in the default location of `/usr/local`, you may have to run `sudo ldconfig` after installation.

**Comment by xxz19900** [comment]
Thank you very much. This bug is fixed in this way.
