### ISSUE TITLE
/usr/local/bin/nucmer: invalid option -- 'm' Use --usage or --help for some help

### ISSUE THREAD

**Issue by xxz19900** [mummer4/mummer#49]
!!! 2017-12-01 02:10:14  Doing step 20:  Getting overlaps 
!!! 2017-12-01 02:10:14  Running: /usr/local/bin/nucmer -maxmatch -c 40 m_i_20.ref.seq m_i_20.qry.seq -p m_i_20
/usr/local/bin/nucmer: invalid option -- 'm'
Use --usage or --help for some help
!!! 2017-12-01 02:10:14  Command: /usr/local/bin/nucmer -maxmatch -c 40 m_i_20.ref.seq m_i_20.qry.seq -p m_i_20 exited with status: 1
!!! END - Elapsed time: 0d 0h 1m 58s

**Comment by skoren** [comment]
You should use ```--maxmatch``` not ```-maxmatch```
