### ISSUE TITLE
autoreconf fails in git checkout

### ISSUE THREAD

**Issue by hjmangalam** [mummer4/mummer#53]
This is an FYI as to the current git checkout.

In git checkout as of today (v4.0.0beta2-2-g277dac5), using the following tools:
1) autoconf/2.69    2) gcc-libs/5.3.0   3) gcc/5.3.0        4) automake/1.15

on CentOS 6.9
$ uname -a
Linux nas-7-1.local 3.10.107-1.el6.elrepo.x86_64 #1 SMP Tue Jun 27 10:57:54 EDT 2017 x86_64 x86_64 x86_64 GNU/Linux

the autoreconf fails with:

$ autoreconf -vfi
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -I m4
autoreconf: configure.ac: tracing
autoreconf: configure.ac: not using Libtool
autoreconf: running: /data/apps/autoconf/2.69/bin/autoconf --force
configure.ac:8: error: possibly undefined macro: AC_PROG_LIBTOOL
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf: /data/apps/autoconf/2.69/bin/autoconf failed with exit status: 1

I saw a previous similar error that suggested using the previously released mummer-4.0.0beta package which contains a preconfigured 'configure'. That package results in a successful configure and make, so there's something a bit odd about the current git.

**Comment by gmarcais** [comment]
You are missing libtool.
