### ISSUE TITLE
make fails under OSX 10.13.3

### ISSUE THREAD

**Issue by splaisan** [mummer4/mummer#54]
I cloned the git and ran 

```
autoreconf -fi
./configure --prefix=/opt/biotools/mummer
make

```
I get

```
make
  YAGGO    src/umd/nucmer_cmdline.hpp
make: *** [src/umd/nucmer_cmdline.hpp] Error 1
```
Any idea?

**Comment by gmarcais** [comment]
Use the release [tarball](https://github.com/mummer4/mummer/releases/download/v4.0.0beta2/mummer-4.0.0beta2.tar.gz), it does not have a dependency on yaggo.

**Comment by aidaph** [comment]
Hi @gmarcais, 

I open this issue again because i get the same problem compiling the version you suggest in the comment, it also depends on YAGGO. 

Is there a way to get out of this dependency commenting something in the configure file?

**Comment by homologus** [comment]
I got the same error trying to compile latest mummer downloaded from git. Is there a "stable" version of the program that works?
