### ISSUE TITLE
compilation error: call to 'ilg' is ambiguous

### ISSUE THREAD

**Issue by svm-zhang** [mummer4/mummer#6]
Hello,

I have been using MUMmer for years, and I am really excited to see an update that provides many many useful features. Thank you very much!

I have been trying to compile from the v3.9.4alpha tarball on my Mac Sierra. It keeps complaining about (I attached the error message in a file here):

[mummer.make.err.txt](https://github.com/gmarcais/mummer/files/671019/mummer.make.err.txt)

I was using the following CMD to do the compilation:

`./configure && make && make install`

Could you please point me where I did wrong? Thanks!

Simo

**Comment by CristianRiccio** [comment]
Hi,
I have the same problem. Have you managed to solve it?
C.

**Comment by gmarcais** [comment]
Fixed in the develop branch. This is due to the Mac using 32-bit long integers for pointer difference. It is fixed.

**Comment by svm-zhang** [comment]
Just want to confirm that the develop branch fixed this problem. Thanks @gmarcais :)
