### ISSUE TITLE
mummer-4.0.0beta2: --genome flag causes core dump

### ISSUE THREAD

**Issue by ckeeling** [mummer4/mummer#86]
I am trying to use dnadiff/nucmer to compare two genomes, each about 250 Mbp and less than 500 scaffolds, but the --genome flag causes a core dump.  I am in a HPC environment, but I am requesting a full node of 125G with 32 cpus. 

offending command:
```
/home/user/bin/mummer-4.0.0beta2/nucmer --genome --threads=31 assembly1.fa assembly2.fa
```

After less than a minute, it ends with:

```
ERROR: Invalid edit matrix entry,
       please file a bug report
/var/spool/slurmd/job14706495/slurm_script: line 29: 151396 Segmentation fault      (core dumped) /home/user/bin/mummer-4.0.0beta2/nucmer --genome --threads=31 assembly1.fa assembly2.fa
```

Without the --genome flag it doesn't immediately crash, but it doesn't properly finish either; dnadiff spends about 22 h making the out.delta and then fails with:

```
ERROR: Failed to run nucmer, aborting.
```

Any suggestions to get this to work?

**Comment by pengbo233** [comment]
--threads=15

**Comment by splaisan** [comment]
look at your RAM during the process, in my case this is the reason for crashing. 
You may have to further lower the number of threads or apply some extra stringency which I am also in need for and wait on the dev to answer about.

**Comment by supermaxiste** [comment]
I can confirm that using 1 thread fixed the issue for the moment
