### ISSUE TITLE
nucmer error: suffix tree construction failed

### ISSUE THREAD

**Issue by tjesser-ucdavis-edu** [mummer4/mummer#91]
I'm having trouble getting a test run of nucmer working.

Running the command

```
$ srun nucmer --mum -f -p Gma_ORIG_SELF Gma_ORIG.fa Gma_ORIG.fa
```

results in the error

```
1: PREPARING DATA
2,3: RUNNING mummer AND CREATING CLUSTERS
# reading input file "Gma_ORIG_SELF.ntref" of length 978496462
# construct suffix tree for sequence of length 978496462
# (maximum reference length is 536870908)
# (maximum query length is 4294967295)
# process 9784964 characters per dot
/usr/bin/mummer: suffix tree construction failed: textlen=978496462 larger than maximal textlen=536870908
ERROR: mummer and/or mgaps returned non-zero
```

MUMmer4 was built from the GitHub release `4.0.0.beta2`, using the suggested

```
./configure --prefix=<dir>
make
make install
```

Is there some way to increase the textlen through a commandline flag or config setting? I looked through the code but couldn't figure anything out.

The environment information:

```
$ nucmer --version
4.0.0beta2
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic
$ cat /proc/cpuinfo | grep -i 'model name' | head -n 1
model name	: Intel(R) Xeon(R) CPU E5-2620 v4 @ 2.10GHz
```

**Comment by tjesser-ucdavis-edu** [comment]
Sorry, the cause ended up being environment confusion with multiple versions of mummer installed.

**Comment by Sameer1028** [comment]
Hi @tjesser-ucdavis-edu , 
I ended up with the same error as you mentioned. But there is no multiple version of mummer installed in my case. Do you have any insights on how to deal with it?

**Comment by Wenwen012345** [comment]
> Hi @tjesser-ucdavis-edu , I ended up with the same error as you mentioned. But there is no multiple version of mummer installed in my case. Do you have any insights on how to deal with it?

You might want to try a conda install instead of apt? The conda (including mamba) install worked for me.
