### ISSUE TITLE
Swig + python + mummer4

### ISSUE THREAD

**Issue by MWorksGH** [mummer4/mummer#99]
I have tried installing swig binning for python with mummer-4.0.0beta2.tar.gz, yet, after installation, I get the following error when trying to import mummer from python: 

`Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "swig/python/mummer.py", line 20, in <module>
  File "swig/python/mummer.py", line 19, in swig_import_helper
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named _mummer`

Also, when checking for python modules with "help('mummer')" it appears installed, yet it outputs:
problem in mummer - <type 'exceptions.ImportError'>: No module named _mummer

Any help will be appreciated. 

BR, 

MWorksGH

**Comment by MWorksGH** [comment]
I've just solved it. :D

**Comment by rshikha95** [comment]
Can you please tell that how did you solve it?

**Comment by rshikha95** [comment]
> I have tried installing swig binning for python with mummer-4.0.0beta2.tar.gz, yet, after installation, I get the following error when trying to import mummer from python:
> 
> `Traceback (most recent call last): File "<string>", line 1, in <module> File "swig/python/mummer.py", line 20, in <module> File "swig/python/mummer.py", line 19, in swig_import_helper File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module __import__(name) ImportError: No module named _mummer`
> 
> Also, when checking for python modules with "help('mummer')" it appears installed, yet it outputs:
> problem in mummer - <type 'exceptions.ImportError'>: No module named _mummer
> 
> Any help will be appreciated.
> 
> BR,
> 
> MWorksGH

Can you please tell that how did you solve it?

**Comment by chenzhiw** [comment]
After compile(make) the code. Copy the /your-path/mummer-4.0.0beta2/swig/python/mummer.py file to /target-path/lib/python/mummer/.
